In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
#from pycaret.clustering import *
#from sklearn.datasets import make_blobs
#mpl.rcParams['figure.dpi'] = 100 #300 сделает картинки большими

from IPython.display import display
from ipywidgets import Dropdown
import ipywidgets as widgets
from ipywidgets import IntSlider


import warnings
warnings.filterwarnings("ignore")


 # Глобальная переменная
#data_tmp = None 
#list_of_feature = None
#city_cut = None

In [ ]:
# ЗАПРОСЫ НА ВЫГРУЗКУ ДАННЫХ

In [21]:
import pandas as pd
from sqlalchemy import create_engine
import csv
from time import sleep
#import paramiko
import shutil
import os
import datetime
import random  
import matplotlib.pyplot as plt
conn_string = 'mssql+pyodbc://corphndw:7V4Kb!dd@HnnDW'
engine = create_engine(conn_string)
connection = engine.connect()

pd.set_option('display.max_columns', None)

In [ ]:
marketshare_path = r'C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\marketshare\marketshare_excel'
df_marketshare = pd.DataFrame()
for filename in os.listdir(marketshare_path):
    df_tmp = pd.read_excel(marketshare_path + '\\' + filename, skiprows=3, sheet_name='Sheet1',header=1, dtype='str')
    df_tmp.drop(columns=['YEAR_WEEK', 'CLIENT', 'SHIP_TO_EX'], inplace=True)
    df_tmp = df_tmp.loc[df_tmp['SHIP_TO'] != 'no_data']
    df_tmp.rename(columns={'YEAR_WEEK.1': 'YEAR_WEEK', 'Total':'MARKET_SHARE'}, inplace=True)
    df_marketshare = pd.concat([df_marketshare, df_tmp])
    df_tmp = pd.DataFrame()

df_marketshare.dropna(inplace=True)
df_marketshare[['SHIP_TO', 'YEAR_WEEK']] = df_marketshare[['SHIP_TO', 'YEAR_WEEK']].astype('int')
df_marketshare['MARKET_SHARE'] = df_marketshare['MARKET_SHARE'].astype('float')
df_marketshare['MARKET_SHARE'] = df_marketshare['MARKET_SHARE'].round(2)

df_marketshare.to_csv(r'C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\marketshare\marketshare_csv\marketshare_2025-2026.csv', sep=';', index=False)

In [13]:
#Выгружаем данные по визитам
sql_query_1 = """
                 SELECT 
                       VISIT_DATE, 
                       SHIP_TO, 
                       ROUTE_ID, 
                       AGENCY_NAME, 
                       PHOTO_AUDIT_ID                 
                 FROM  HnnDW.dbo.Fact_Visits 
                 WHERE VISIT_DATE >= '2026-01-01 00:00:00.000'   AND 
                       VISIT_DATE <= '2026-06-30 23:59:59.999'   AND 
                       PHOTO_AUDIT_COUNTER  = 2                  AND 
                       ROUTE_TYPE = N'Мерчандайзер'              AND 
                       AGENCY_NAME  NOT IN ('HnN', 'Agencytest') AND 
                       VISIT_IS_PLANED = 1                       AND                       
                       VISIT_IS_COMPLETE = 1                     AND 
                       isInvalid = 0                       
            """   
df_fact_visits = pd.read_sql(sql_query_1, connection)
path_1 = r"C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\visits\df_fact_visits_01-06_2026.csv"
df_fact_visits.to_csv(path_1, sep=';', index=False)

In [ ]:
#Выгружаем данные по OSA
sql_query_2 = """
  SELECT OSA.VISIT_DATE, 
         OSA.PHOTO_AUDIT_ID, 
         OSA.SHIP_TO, 
         round(sum(OSA.IN_STOCK)*1.0/sum(OSA.IN_MATRIX), 2) AS OSA  
         FROM (SELECT VISIT_DATE, 
                        PHOTO_AUDIT_ID, 
                        SHIP_TO, 
                        PRODUCT_NATURE_CD, 
                        CASE      WHEN sum(IN_STOCK) > 0   THEN   1   ELSE 0   END AS IN_STOCK,
                        CASE      WHEN sum(IN_MATRIX) > 0  THEN   1   ELSE 0   END AS IN_MATRIX
                 FROM HnnDW.dbo.Fact_OSA 
                 WHERE 
                        VISIT_DATE >= '2026-01-01 00:00:00.000'    AND 
                        VISIT_DATE <= '2026-06-30 23:59:59.999'    AND 
                        PHOTO_AUDIT_COUNTER  = 2                   AND 
                        ROUTE_TYPE = N'Мерчандайзер'               AND 
                        AGENCY_NAME  NOT IN ('HnN', 'Agencytest')  AND 
                        VISIT_IS_PLANED = 1                        AND 
                        IN_MATRIX > 0
                 GROUP BY VISIT_DATE, PHOTO_AUDIT_ID, SHIP_TO, PRODUCT_NATURE_CD) AS OSA
GROUP BY VISIT_DATE, PHOTO_AUDIT_ID, SHIP_TO
            """   
df_fact_osa = pd.read_sql(sql_query_2, connection)
path_1 = r"C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\osa\df_fact_osa_01-06_2026.csv"
df_fact_osa.to_csv(path_1, sep=';', index=False)

In [16]:
#Выгружаем балл PICOS
sql_query_7 = """
             SELECT VISIT_DATE, PHOTO_AUDIT_ID, SHIP_TO, PICOS_SCORE_FACT, PICOS_TARGET_SCORE
                 FROM HnnDW.dbo.FACT_PICOS
                 WHERE 
                        VISIT_DATE >= '2026-01-01 00:00:00.000'    AND 
                        VISIT_DATE <= '2026-06-30 23:59:59.999'    AND 
                        PHOTO_AUDIT_COUNTER  = 2                   AND 
                        ROUTE_TYPE = N'Мерчандайзер'               AND 
                        AGENCY_NAME  NOT IN ('HnN', 'Agencytest')  AND 
                        VISIT_IS_PLANED = 1                        AND
                        PICOS_ELEMENT   IN ('Итоговый балл PICOS') 
      
            """   
df_FACT_PICOS = pd.read_sql(sql_query_7, connection)
path_7 = r"C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\picos\df_fact_picos_01-06_2026.csv"
df_FACT_PICOS.to_csv(path_7, sep=';', index=False)

In [ ]:
#Выгружаем фейсы на ОХП (все)
sql_query_8 = """
             SELECT VISIT_DATE, PHOTO_AUDIT_ID, SHIP_TO, sum(GROUP_FACT) AS GROUP_FACT
                 FROM HnnDW.dbo.Fact_Facing 
                 WHERE 
                        VISIT_DATE >= '2026-01-01 00:00:00.000'    AND 
                        VISIT_DATE <= '2026-06-30 23:59:59.999'    AND 
                        PHOTO_AUDIT_COUNTER  = 2                   AND 
                        ROUTE_TYPE = N'Мерчандайзер'               AND 
                        AGENCY_NAME  NOT IN ('HnN', 'Agencytest')  AND 
                        VISIT_IS_PLANED = 1                        AND 
                        PRODUCER = 'Danone'                        AND 
                        SCENE_TYPE_ID = '50041' 
                 GROUP BY   VISIT_DATE, PHOTO_AUDIT_ID, SHIP_TO
      
            """   
df_Fact_Facing = pd.read_sql(sql_query_8, connection)
path_8 = r"C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\facing\df_fact_facing_01-06_2026.csv"
df_Fact_Facing.to_csv(path_8, sep=';', index=False)

In [7]:
#Выгружаем данные по доле полки на ОХП
sql_query_88 = """
             SELECT FC.VISIT_DATE, 
                    FC.PHOTO_AUDIT_ID, 
                    FC.SHIP_TO, 
                    sum(CASE WHEN SKU.PRODUCER = 'Danone' THEN FC.GROUP_FACT ELSE 0 END) / sum(FC.GROUP_FACT) * 1.0   AS SHELF_SHARE
                 FROM HnnDW.dbo.Fact_Facing  AS FC
                 LEFT JOIN HnnDW.dbo.Dim_Products AS SKU
                 ON SKU.PRODUCT_NATURE_CD = FC.PRODUCT_NATURE_CD 
                 WHERE 
                        FC.VISIT_DATE >= '2026-01-01 00:00:00.000'    AND 
                        FC.VISIT_DATE <= '2026-06-30 23:59:59.999'    AND 
                        FC.PHOTO_AUDIT_COUNTER  = 2                   AND 
                        FC.ROUTE_TYPE = N'Мерчандайзер'               AND 
                        FC.AGENCY_NAME  NOT IN ('HnN', 'Agencytest')  AND 
                        FC.VISIT_IS_PLANED = 1                        AND 
                        FC.SCENE_TYPE_ID = '50041' 
                 GROUP BY   FC.VISIT_DATE, FC.PHOTO_AUDIT_ID, FC.SHIP_TO
      
            """   
df_shelfshare = pd.read_sql(sql_query_88, connection)
path_88 = r"C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\shelfshare\df_shelfshare_01-06_2026.csv"
df_shelfshare.to_csv(path_88 , sep=';', index=False)
df_shelfshare

       VISIT_DATE              PHOTO_AUDIT_ID    SHIP_TO  SHELF_SHARE
0      2026-07-01  3007383_1146142_20260701_2  850023823     0.259388
1      2026-07-01  3006172_1146148_20260701_2  850023988     0.229072
2      2026-07-01  3001129_1018963_20260701_2  850023998     0.297994
3      2026-07-01  3007038_1000006_20260701_2  850024084     0.234837
4      2026-07-01  2004328_1023843_20260701_2  850024306     0.208498
...           ...                         ...        ...          ...
496485 2026-03-31  3005697_1011959_20260331_2  850279524     0.397759
496486 2026-03-31  3003917_1007937_20260331_2  850194904     0.515249
496487 2026-03-31  3003772_1412133_20260331_2  850294977     0.410526
496488 2026-03-31  2004107_1400993_20260331_2  850112090     0.350211
496489 2026-03-31  2004230_1094705_20260331_2  850115139     0.224645

[496490 rows x 4 columns]

In [ ]:
#Выгружаем данные по ТТ
sql_query_3 = """
                 SELECT  *
                 FROM HnnDW.dbo.Dim_POSList 
                 WHERE AGENCY_NAME = 'OPEN'  
      
            """   
df_Dim_POSList = pd.read_sql(sql_query_3, connection)
path_1 = r"C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\dim_poslist.csv"
df_Dim_POSList.to_csv(path_1, sep=';', index=False)

In [ ]:
# ЗАГРУЗКА И ПОДГОТОВКА ДАННЫХ В ДАТАФРЕЙМ

In [18]:
import pandas as pd
import os
#
osa_path = r'C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\osa'
df_osa = pd.DataFrame()
for filename in os.listdir(osa_path):
    df_tmp = pd.read_csv(osa_path + '\\' + filename, sep=';', dtype='str')
    df_osa = pd.concat([df_osa, df_tmp])
    df_tmp = pd.DataFrame()

In [ ]:
df_osa['VISIT_DATE'] = pd.to_datetime(df_osa['VISIT_DATE'])
df_osa[['SHIP_TO']] = df_osa[['SHIP_TO']].astype('int')
df_osa[['OSA']] = df_osa[['OSA']].astype('float')
#
df_osa['YEAR'] = df_osa['VISIT_DATE'].dt.year
df_osa['MONTH'] = df_osa['VISIT_DATE'].dt.month
df_osa['WEEK'] = df_osa['VISIT_DATE'].dt.isocalendar().week
df_osa[['YEAR', 'MONTH','WEEK']] = df_osa[['YEAR', 'MONTH','WEEK']].astype('int')
df_osa['YEAR_MONTH'] = ''
df_osa['YEAR_WEEK'] = ''
df_osa.loc[df_osa['MONTH'] < 10, 'YEAR_MONTH'] = '0'
df_osa.loc[df_osa['WEEK'] < 10, 'YEAR_WEEK'] = '0'
df_osa['YEAR_MONTH'] = df_osa['YEAR'].astype('str') + df_osa['YEAR_MONTH'] + df_osa['MONTH'].astype('str') 
df_osa['YEAR_MONTH'] = df_osa['YEAR_MONTH'].astype('int')

df_osa['YEAR_WEEK'] = df_osa['YEAR'].astype('str') + df_osa['YEAR_WEEK'] + df_osa['WEEK'].astype('str') 
df_osa['YEAR_WEEK'] = df_osa['YEAR_WEEK'].astype('int')
#
### Блок аггрегации
#
#df_osa = df_osa.groupby(by=['YEAR_MONTH', 'SHIP_TO']).agg({'IN_STOCK':sum, 'IN_MATRIX':sum }).reset_index()
#df_osa['OSA'] =  round(df_osa['IN_STOCK'] / df_osa['IN_MATRIX'] * 100, 1)
#
#df_osa.head(2)

,VISIT_DATE,PHOTO_AUDIT_ID,SHIP_TO,OSA,YEAR,MONTH,YEAR_MONTH,WEEK,YEAR_WEEK
0,2026-07-01,3007383_1146142_20260701_2,850023823,0.98,2026,7,202607,27,202627
1,2026-07-01,3006172_1146148_20260701_2,850023988,0.95,2026,7,202607,27,202627

In [ ]:
#import pandas as pd
#import os
#
#osa_path = r'C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\osa'
#df_osa = pd.DataFrame()
#for filename in os.listdir(osa_path):
#    df_tmp = pd.read_csv(osa_path + '\\' + filename, sep=';', dtype='str')
#    df_osa = pd.concat([df_osa, df_tmp])
#    df_tmp = pd.DataFrame()
#
#df_osa['VISIT_DATE'] = pd.to_datetime(df_osa['VISIT_DATE'])
#df_osa[['SHIP_TO', 'PRODUCT_NATURE_CD', 'IN_STOCK', 'IN_MATRIX']] = df_osa[['SHIP_TO', 'PRODUCT_NATURE_CD', 'IN_STOCK', 'IN_MATRIX']].astype('int')
#
#df_osa['YEAR'] = df_osa['VISIT_DATE'].dt.year
#df_osa['MONTH'] = df_osa['VISIT_DATE'].dt.month
#df_osa[['YEAR', 'MONTH']] = df_osa[['YEAR', 'MONTH']].astype('int')
#df_osa['YEAR_MONTH'] = ''
#df_osa.loc[df_osa['MONTH'] < 10, 'YEAR_MONTH'] = '0'
#df_osa['YEAR_MONTH'] = df_osa['YEAR'].astype('str') + df_osa['YEAR_MONTH'] + df_osa['MONTH'].astype('str') 
#df_osa['YEAR_MONTH'] = df_osa['YEAR_MONTH'].astype('int')
#
### Блок аггрегации
#
#df_osa = df_osa.groupby(by=['YEAR_MONTH', 'SHIP_TO']).agg({'IN_STOCK':sum, 'IN_MATRIX':sum }).reset_index()
#df_osa['OSA'] =  round(df_osa['IN_STOCK'] / df_osa['IN_MATRIX'] * 100, 1)
#
##df_osa.head(2)

In [ ]:
sales_path = r'C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\sales'
df_sales = pd.DataFrame()
for filename in os.listdir(sales_path):
    df_tmp = pd.read_csv(sales_path + '\\' + filename, sep=',', dtype='str')
    df_sales = pd.concat([df_sales, df_tmp])
    df_tmp = pd.DataFrame()
    
df_sales.rename(columns={'(CUS) Ship To Code': 'SHIP_TO', '(CUS-DC) Customer Group':'CUSTOMER_GROUP', '(CUS-DC) Proxi Category 2':'CLIENT', '(CUS-DC) Proxi Category 3':'CHANNEL', 'Month':'YEAR_MONTH', 'Year':'YEAR' }, inplace=True)
df_sales = df_sales.query("CHANNEL in ('NATIONAL KEY ACCOUNT', 'LOCAL KEY ACCOUNT')")
df_sales.drop(columns=['(CUS) Ship To Address', '(CUS) Ship To', 'Client MacroGroup' ], inplace=True)
#df_sales['VISIT_DATE'] = pd.to_datetime(df_sales['VISIT_DATE'])
df_sales[['SHIP_TO', 'YEAR_MONTH', 'YEAR']] = df_sales[['SHIP_TO', 'YEAR_MONTH', 'YEAR']].astype('int')
df_sales['kCAF'] = df_sales['kCAF'].astype('float')

#df_sales.head(10)

In [ ]:
visits_path = r'C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\visits'
df_visits = pd.DataFrame()
for filename in os.listdir(visits_path):
    df_tmp = pd.read_csv(visits_path + '\\' + filename, sep=';', dtype='str')
    df_visits = pd.concat([df_visits, df_tmp])
    df_tmp = pd.DataFrame()
    
df_visits['VISIT_DATE'] = pd.to_datetime(df_visits['VISIT_DATE'])
df_visits['SHIP_TO'] = df_visits['SHIP_TO'].astype('int')

df_visits['YEAR'] = df_visits['VISIT_DATE'].dt.year
df_visits['MONTH'] = df_visits['VISIT_DATE'].dt.month
df_visits[['YEAR', 'MONTH']] = df_visits[['YEAR', 'MONTH']].astype('int')
df_visits['YEAR_MONTH'] = ''
df_visits.loc[df_visits['MONTH'] < 10, 'YEAR_MONTH'] = '0'
df_visits['YEAR_MONTH'] = df_visits['YEAR'].astype('str') + df_visits['YEAR_MONTH'] + df_visits['MONTH'].astype('str') 
df_visits['YEAR_MONTH'] = df_visits['YEAR_MONTH'].astype('int')

## Блок аггрегации

df_visits = df_visits.groupby(by=['YEAR_MONTH', 'SHIP_TO']).agg({'PHOTO_AUDIT_ID':'size'}).reset_index()
df_visits.rename(columns={'PHOTO_AUDIT_ID': 'PHOTO_AUDITS_PER_MONTH'}, inplace=True)


#df_visits.head(2)

In [ ]:
df_pos_list = pd.read_csv(r"C:\Users\rokotyev\Yandex.Disk\_Main Data Rokotyan\2. Проекты\60. Подбор пар ТТ для тестов\_data\dim_poslist.csv", sep=';', dtype='str')
df_pos_list[['SHIP_TO', 'fid']] = df_pos_list[['SHIP_TO', 'fid']].astype('int')
df_pos_list[['LATITUDE', 'LONGITUDE']] = df_pos_list[['LATITUDE', 'LONGITUDE']].astype('float')

#print(df_pos_list.shape)
#df_pos_list.dtypes

# ЗАГРУЗКА СПИСКА ТЕСТОВЫХ ТОЧЕК

---

In [ ]:
import ipywidgets as widgets
import pandas as pd
import io
from IPython.display import display, clear_output

test_pos_list = []

# Создаём виджет загрузки (только .xlsx файлы)
uploader = widgets.FileUpload(accept='.xlsx',
                              multiple=False,
                              description='Загрузка списка тестовых ТТ',
                              layout=widgets.Layout(width='20%', height='40px'),
                              button_style='warning'                              
                              )
output_file = widgets.Output()

def on_upload(change):
    global test_pos_list
    if uploader.value:
        # Получаем первый загруженный файл
        uploaded_file = uploader.value[0]
        content = uploaded_file['content']
        print(content)
        # Читаем Excel из байтов
        test_pos_list = pd.read_excel(io.BytesIO(content))
        with output_file:
            clear_output()
            print("Загружено строк: " + str(test_pos_list.shape[0]) )
            #display(test_pos_list.head(5))  # Показываем первые строки

uploader.observe(on_upload, names='value')
display(widgets.VBox([uploader, output_file]))

-----

# ВЫБОР ПАРАМЕТРОВ ПОДБОРА ПАР

-----

#### ВЫБОР ТЕРРИТОРИАЛЬНЫХ ОГРАНИЧЕНИЙ:

In [ ]:
# Удобный выбор территориальных признаков

from IPython.display import display
from ipywidgets import Dropdown
import ipywidgets as widgets
from ipywidgets import IntSlider
#options = data.columns.to_list()[7:len(data.columns.to_list()) + 1]
feature_list =[]
options =  ['RSD', 'BUSINESS_UNIT', 'SALES_GROUP', 'CLIENT', 'CUSTOMER_GROUP', 'CITY']


# Создаем чекбоксы для каждой опции
checkboxes = [widgets.Checkbox(value=False, description=option) for option in options]


# Функция для обработки нажатия на отдельный чек-бокс - записываем список выбранных фич в глоб. переменную feature_list
def on_change_feature(change):
    global feature_list
    selected = sorted([checkbox.description for checkbox in checkboxes if checkbox.value])
    feature_list = selected  # Объявляем, что используем глобальную переменную
    print(feature_list)
    with output_feature: # Этот блок печатает список
         output_feature.clear_output()  
         print(f'Для поиска пар будут использоваться только точки с одинаковыми: {feature_list}')  


# Запускаем мониторинг изменений на каждом чекбоксе (событие observe означает изменеие )
for checkbox in checkboxes:
    checkbox.observe(on_change_feature, names='value')

# Отображаем чекбоксы на экране
output_feature = widgets.Output()



wig = widgets.VBox([widgets.GridBox(checkboxes, layout=widgets.Layout(grid_template_columns="repeat(2, 250px)"))])
display(wig, output_feature)

---

#### ВЫБОР ВРЕМЕННОГО ПЕРИОДА ДЛЯ РАСЧЁТА KPI:

In [ ]:
# Удобный выбор временного периода
month_list =[]
options_month =  list(map(str, df_sales['YEAR_MONTH'].unique()))


# Создаем чекбоксы для каждой опции
checkboxes_month = [widgets.Checkbox(value=False, description=option) for option in options_month]


# Функция для обработки нажатия на отдельный чек-бокс - записываем список выбранных фич в глоб. переменную feature_list
def on_change_month(change):
    global month_list
    selected = sorted([checkbox.description for checkbox in checkboxes_month if checkbox.value])
    month_list = selected  # Объявляем, что используем глобальную переменную
    with output_month: # Этот блок печатает список
         output_month.clear_output()  
         print(f'Для поиска пар будут расчитаны KPI только за выбранный период: {month_list}')  


# Запускаем мониторинг изменений на каждом чекбоксе (событие observe означает изменеие )
for checkbox in checkboxes_month:
    checkbox.observe(on_change_month, names='value')

# Отображаем чекбоксы на экране
output_month = widgets.Output()



wig_month = widgets.VBox([widgets.GridBox(checkboxes_month, layout=widgets.Layout(grid_template_columns="repeat(3, 250px)"))])
display(wig_month, output_month)

---

#### ВЫБОР KPI ДЛЯ ПОДБОРА ПАР:

In [ ]:
import ipywidgets as widgets
from IPython.display import display, clear_output

options_kpi = ['kCAF', 'OSA', 'VISITS']

kpi_list = []
kpi_ranges = {}
checkboxes = {}
sliders = {}
rows = {}

output = widgets.Output()

def sync_globals():
    global kpi_list, kpi_ranges
    kpi_list = [name for name in options_kpi if checkboxes[name].value]
    kpi_ranges = {name: sliders[name].value for name in kpi_list}
    for name in kpi_list:
        globals()[f'kpi_{name}'] = sliders[name].value

def redraw_output():
    with output:
        clear_output(wait=True)
        print(f"Выбранные KPI: {kpi_list}")
        print("Диапазоны KPI:")
        for name in kpi_list:
            print(f"{name}: {sliders[name].value}")

def on_checkbox_change(change):
    kpi_name = change.owner.description
    if change.new:
        sliders[kpi_name].layout.display = 'flex'
    else:
        sliders[kpi_name].layout.display = 'none'
        if f'kpi_{kpi_name}' in globals():
            globals().pop(f'kpi_{kpi_name}', None)
    sync_globals()
    redraw_output()

def on_slider_change(change):
    kpi_name = change.owner.description
    globals()[f'kpi_{kpi_name}'] = change.new
    sync_globals()
    redraw_output()

for name in options_kpi:
    cb = widgets.Checkbox(value=False, description=name, layout=widgets.Layout(width='150px'))
    sl = widgets.FloatRangeSlider(
        value=(0.5, 1.5),
        min=0.0,
        max=3.0,
        step=0.1,
        description='',
        continuous_update=False,
        layout=widgets.Layout(width='350px', display='none')
    )

    cb.observe(on_checkbox_change, names='value')
    sl.observe(on_slider_change, names='value')

    checkboxes[name] = cb
    sliders[name] = sl
    rows[name] = widgets.HBox([cb, sl])

ui = widgets.VBox([rows[name] for name in options_kpi])

display(ui, output)

sync_globals()
redraw_output()

In [ ]:
# БЛОК ПОИСКА ПАР

---

In [ ]:
#Обрезамем данные по KPI согласно выбранным месяцам и считаем среднее по оставшимся

def cut_dataframes(month_list, df_sales, df_osa, df_visits ):
    se_month_list = pd.Series(map(int, month_list), name = 'YEAR_MONTH')

    df_sales_cut = pd.DataFrame(df_sales)
    df_sales_cut = df_sales.merge(se_month_list, on='YEAR_MONTH', how='inner')
    df_sales_cut = df_sales_cut.groupby(by=['SHIP_TO']).agg({'kCAF':'mean' }).reset_index()


    df_osa_cut = pd.DataFrame(df_osa)
    df_osa_cut = df_osa_cut.merge(se_month_list, on='YEAR_MONTH', how='inner')
    df_osa_cut = df_osa_cut.groupby(by=['SHIP_TO']).agg({'OSA':'mean' }).reset_index()

    df_visits_cut = pd.DataFrame(df_visits)
    df_visits_cut = df_visits_cut.merge(se_month_list, on='YEAR_MONTH', how='inner')
    df_visits_cut = df_visits_cut.groupby(by=['SHIP_TO']).agg({'PHOTO_AUDITS_PER_MONTH':'mean' }).reset_index()
    return df_sales_cut, df_osa_cut, df_visits_cut

In [ ]:
# Для точек плдтягиваем KPI

def calc_kpi_for_test_pos(df_pos_list, df_sales_cut, df_osa_cut, df_visits_cut ):

    df_pos_list_with_kpi = pd.DataFrame(df_pos_list)

    if 'OSA' in kpi_list: 
        df_pos_list_with_kpi = df_pos_list_with_kpi.merge(df_osa_cut, on='SHIP_TO', how='left', indicator=True )
        #df_pos_list = df_pos_list.loc[df_pos_list['_merge'] != 'right_only'].reset_index().drop(columns='index')
        df_pos_list_with_kpi['_merge'] = df_pos_list_with_kpi['_merge'].astype('string')
        df_pos_list_with_kpi.rename(columns={'_merge': 'DATA_IN_OSA' }, inplace=True)
        df_pos_list_with_kpi.replace({'DATA_IN_OSA' : { 'both' : 'Ok', 'left_only' : 'No_OSA_data'}}, inplace=True)

    if 'kCAF' in kpi_list: 
        df_pos_list_with_kpi = df_pos_list_with_kpi.merge(df_sales_cut, on='SHIP_TO', how='left', indicator=True )
        #df_pos_list = df_pos_list.loc[df_pos_list['_merge'] != 'right_only'].reset_index().drop(columns='index')
        df_pos_list_with_kpi['_merge'] = df_pos_list_with_kpi['_merge'].astype('string')
        df_pos_list_with_kpi.rename(columns={'_merge': 'DATA_IN_SALES' }, inplace=True)
        df_pos_list_with_kpi.replace({'DATA_IN_SALES' : { 'both' : 'Ok', 'left_only' : 'No_SALES_data'}}, inplace=True)

    if 'VISITS' in kpi_list: 
        df_pos_list_with_kpi = df_pos_list_with_kpi.merge(df_visits_cut, on='SHIP_TO', how='left', indicator=True )
        #df_pos_list = df_pos_list.loc[df_pos_list['_merge'] != 'right_only'].reset_index().drop(columns='index')
        df_pos_list_with_kpi['_merge'] = df_pos_list_with_kpi['_merge'].astype('string')
        df_pos_list_with_kpi.rename(columns={'_merge': 'DATA_IN_VISITS' }, inplace=True)
        df_pos_list_with_kpi.replace({'DATA_IN_VISITS' : { 'both' : 'Ok', 'left_only' : 'No_VISITS_data'}}, inplace=True)

    df_pos_list_with_kpi['PAIR_NUMBER'] = 0
    df_pos_list_with_kpi['POS_TYPE'] = '-'
    return df_pos_list_with_kpi

In [ ]:
global df_pair_list
df_pair_list = pd.DataFrame([])


def find_pairs(test_pos_list, df_pos_list_with_kpi):

    global df_pair_list
    df_pair_list = pd.DataFrame([])
    
    
    
    for index, df_row in test_pos_list.iterrows():
        #Сохраняем данные по тестовой точке
        
        df_one_test_pos = df_pos_list_with_kpi.loc[df_pos_list_with_kpi['SHIP_TO'] ==  df_row['SHIP_TO']].reset_index()
        if df_one_test_pos.shape[0] == 0:
            df_one_test_pos.loc[0, ['SHIP_TO', 'RSD' ]] = [df_row['SHIP_TO'], 'POS not found in Optimum']
        df_one_test_pos['PAIR_NUMBER'] = index + 1
        df_one_test_pos['POS_TYPE'] = 'Test_POS'
        
        df_pair_list = pd.concat([df_pair_list, df_one_test_pos])
        df_pair_list = df_pair_list.reset_index().drop(columns=['index', 'level_0'])
        df_pair_list['SHIP_TO'] = df_pair_list['SHIP_TO'].astype('int')
        df_pair_list['PAIR_NUMBER'] = df_pair_list['PAIR_NUMBER'].astype('int')   
    
    
        ## Подбираем контрольную точку по территории
    
        df_used_pos = pd.DataFrame(pd.Series(pd.concat([pd.DataFrame(df_pair_list['SHIP_TO']), test_pos_list])['SHIP_TO'].unique(), name='SHIP_TO'))
        df_one_control_pos =  df_pos_list_with_kpi.merge(df_used_pos, how='left', on='SHIP_TO', indicator=True)
        df_one_control_pos =  df_one_control_pos.loc[df_one_control_pos['_merge'] == 'left_only'].drop(columns='_merge')
    
    
        if 'RSD' in feature_list:
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['RSD'] == df_one_test_pos['RSD'][0]  ]
        if 'BUSINESS_UNIT' in feature_list:
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['BUSINESS_UNIT'] == df_one_test_pos['BUSINESS_UNIT'][0]  ]
        if 'SALES_GROUP' in feature_list:
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['SALES_GROUP'] == df_one_test_pos['SALES_GROUP'][0]  ]
        if 'CITY' in feature_list:
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['CITY'] == df_one_test_pos['CITY'][0]  ]
        if 'CLIENT' in feature_list:
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['CLIENT'] == df_one_test_pos['CLIENT'][0]  ]
        if 'CUSTOMER_GROUP' in feature_list:
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['CUSTOMER_GROUP'] == df_one_test_pos['CUSTOMER_GROUP'][0]  ]
        
            ## Подбираем контрольную точку по KPI
        if 'OSA' in kpi_list: 
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['OSA'] >= df_one_test_pos['OSA'][0]   *    kpi_ranges['OSA'][0] ]
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['OSA'] <= df_one_test_pos['OSA'][0]   *    kpi_ranges['OSA'][1] ]
        if 'kCAF' in kpi_list: 
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['kCAF'] >= df_one_test_pos['kCAF'][0]   *   kpi_ranges['kCAF'][0]  ]
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['kCAF'] <= df_one_test_pos['kCAF'][0]   *   kpi_ranges['kCAF'][1]  ]
        if 'VISITS' in kpi_list: 
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['PHOTO_AUDITS_PER_MONTH'] >= df_one_test_pos['PHOTO_AUDITS_PER_MONTH'][0]   *    kpi_ranges['VISITS'][0]  ]
            df_one_control_pos = df_one_control_pos.loc[df_one_control_pos['PHOTO_AUDITS_PER_MONTH'] <= df_one_test_pos['PHOTO_AUDITS_PER_MONTH'][0]   *    kpi_ranges['VISITS'][1]  ]
        
        
        if df_one_control_pos.shape[0] > 0: 
            df_one_control_pos = df_one_control_pos.head(1)
            df_one_control_pos['PAIR_NUMBER'] = index + 1
            df_one_control_pos['POS_TYPE'] = 'Control_POS'
            df_pair_list = pd.concat([df_pair_list, df_one_control_pos])
        else: 
            df_pair_list.loc[(df_pair_list['SHIP_TO'] == df_row['SHIP_TO']) & (df_pair_list['POS_TYPE'] == 'Test_POS'), 'POS_TYPE' ] = 'Test_POS_wo_pair'
    return df_pair_list

# ПОДБОР ПАР И ВЫГРУЗКА РЕЗУЛЬТАТОВ

In [ ]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# Глобальная переменная, чтобы она существовала заранее


def on_calculate_click(button):
    
    output_calc.clear_output()
    
    with output_calc:
        try:
            df_sales_cut, df_osa_cut, df_visits_cut = cut_dataframes(month_list, df_sales, df_osa, df_visits )
            df_pos_list_with_kpi = calc_kpi_for_test_pos(df_pos_list, df_sales_cut, df_osa_cut, df_visits_cut )
            df_pair_list = find_pairs(test_pos_list, df_pos_list_with_kpi)
            print(df_pair_list)
            #display(df_pair_list)
            print("Все функции успешно выполнены")
        except Exception as e:
            print(f"Ошибка: {e}")
    return df_pair_list

calculate_button = widgets.Button(
    description='Рассчитать',
    layout=widgets.Layout(width='20%', height='40px'),
    button_style='danger',
    icon='check'
)


output_calc = widgets.Output()

calculate_button.on_click(on_calculate_click)

display(widgets.VBox([calculate_button, output_calc]))

---

In [ ]:
import os
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# Поле для ввода пути к файлу
path_widget = widgets.Text(
    value='./result.xlsx',
    placeholder='Например: C:/temp/df_pair_list.xlsx или ./df_pair_list.xlsx',
    description='Путь:',
    layout=widgets.Layout(width='700px')
)

# Чекбокс: сохранять ли индекс
index_widget = widgets.Checkbox(
    value=False,
    description='Сохранять индекс'
)

# Кнопка экспорта
export_button = widgets.Button(
    description='Выгрузить в Excel',
    layout=widgets.Layout(width='20%', height='40px'),
    button_style='success',
    icon='download'
)

# Поле для сообщений
output = widgets.Output()

def export_to_excel(button):
    with output:
        output.clear_output()
        
        try:
            file_path = path_widget.value.strip()
            
            if not file_path:
                print("Ошибка: укажите путь к файлу.")
                return
            
            if not file_path.lower().endswith('.xlsx'):
                file_path += '.xlsx'
            
            # Создаем папку, если она указана и не существует
            dir_name = os.path.dirname(file_path)
            if dir_name:
                os.makedirs(dir_name, exist_ok=True)
            
            # Проверка, что df_pair_list существует
            if 'df_pair_list' not in globals():
                print("Ошибка: DataFrame df_pair_list не найден.")
                return
            
            # Экспорт в Excel
            df_pair_list.to_excel(file_path, index=index_widget.value)
            
            print(f"Файл успешно сохранён: {os.path.abspath(file_path)}")
        
        except Exception as e:
            print(f"Ошибка при сохранении файла: {e}")

export_button.on_click(export_to_excel)

ui = widgets.VBox([
    path_widget,
    index_widget,
    export_button,
    output
])

display(ui)